### ISSUE TITLE
Incompatibility on Asterisk 18?

### ISSUE THREAD

**Issue by jouytxi** [elpop/sipban#3]
Hi, 

I've just installed an Asterisk 18, to test SIPBAN and after several registration failures no IP addresses are blocked:

`
[Jun 23 10:22:21] NOTICE[3606] res_pjsip/pjsip_distributor.c: Request 'REGISTER' from '<sip:XXXX@XXXXXXXX>' failed for 'YYYYYYYY:5062' (callid: 333253047-5062-9@BJC.BGI.H.BJJ) - Failed to authenticate
`
After enabling AMI debug the events reported From Asterisk are ChallengeResponseFailed and I can't see this type of events on the code:

```
Event: ChallengeResponseFailed
Privilege: security,all
SequenceNumber: 67
File: manager.c
Line: 1864
Func: manager_default_msg_cb
EventTV: 2021-06-23T10:22:21.751+0200
Severity: Error
Service: PJSIP
EventVersion: 1
AccountID: XXXX
SessionID: 333253047-5062-9@BJC.BGI.H.BJJ
LocalAddress: IPV4/UDP/XXXXXXXX/5060
RemoteAddress: IPV4/UDP/YYYYYYYY/5062
Challenge: 1624436541/3c34d6746cc5187774c60cd18cf793ce
Response: ffc167de33082dadd87a6479d9795c3f
ExpectedResponse:
```
I don't know if the Asterisk team ha changed anything but inside the Asterisk documentation, this type of event is defined since Asterisk 13:

https://wiki.asterisk.org/wiki/display/AST/Asterisk+13+ManagerEvent_ChallengeResponseFailed

Could you please update the script?

Thank you

**Comment by elpop** [comment]
SipBan use two AMI events:

        Event: InvalidAccountID
        Privilege: security,all
        EventTV: 2019-06-07T21:25:59.559+0000
        Severity: Error
        Service: PJSIP
        EventVersion: 1
        AccountID: 55001
        SessionID: 99260YTExOWI2Y2NjZTVhODQ4NTVmMmZjMDc1MWUwMzY3MTM
        LocalAddress: IPV4/UDP/10.211.55.8/5060
        RemoteAddress: IPV4/UDP/10.211.55.2/59977

        Event: InvalidPassword
        Privilege: security,all
        EventTV: 2019-06-07T21:17:59.819+0000
        Severity: Error
        Service: SIP
        EventVersion: 2
        AccountID: 5500
        SessionID: 0x7f8db400d860
        LocalAddress: IPV4/UDP/10.211.55.8/5060
        RemoteAddress: IPV4/UDP/10.211.55.2/52551
        Challenge: 79cca43d
        ReceivedChallenge: 79cca43d
        ReceivedHash: 91801011d87fe17fca4aca4893f9920d

both are present in * 18.x.x using the manager "security" profile

Sipban works without problem in Asterisk 18, check if your AMI conf file is correct:

[general]
enabled = yes

port = 5038
bindaddr = 127.0.0.1

[sipban]
secret = getout
writetimeout = 100000
read = security
write = system,command

Let me check the event reported by you and see if is usefully in the detection of attacks

**Comment by elpop** [comment]
@asternic put a solution for this in the las version, please pull and test
