### ISSUE TITLE
Almalinux 8 test

### ISSUE THREAD

**Issue by rickygm** [elpop/sipban#6]
Hi, I'm doing tests and the service fails

sipban.service - SIP Ban Service
   Loaded: loaded (/etc/systemd/system/sipban.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2023-05-08 11:24:58 CST; 162ms ago
  Process: 30137 ExecStart=/usr/local/bin/sipban.pl (code=exited, status=2)
 Main PID: 30137 (code=exited, status=2)

`/etc/systemd/system/sipban.service:6: Failed to parse service type, ignoring: service`

I made the change in this line:

`Type=service`

to

`Type=notify`

but without success

**Comment by elpop** [comment]
What distro use?

Whit Ubuntu and Fedora, the instructions for service config, work without problems

**Comment by rickygm** [comment]
Almalinux 8

**Comment by elpop** [comment]
sorry for the delay, when you change a service definition, must put the following command:

systemctl daemon-reload

prior to start or stop a service.

**Comment by rickygm** [comment]
Hi, I had already solved it some time ago, the problem was some perl libraries that were not.

thnk
